name: head_copy_cw_trainer
description: A CW (Morse code) trainer using the Koch method.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18
  path_provider: ^2.1.2
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cw-words.txt
    - assets/common-english-words.txt
    - assets/qsos.txt
    - assets/callsigns.txt
    - assets/HELP.md
